### ISSUE TITLE
Can't npm install -g yo

### ISSUE THREAD

**Issue by kimpetersend1** [yeoman/yo#302] opened 2015-02-24 12:09 UTC
![yo](https://cloud.githubusercontent.com/assets/8875499/6349023/ac7e4eb0-bc2e-11e4-895a-80c204092cfc.PNG)

This is what happens when I try to install yeoman, can you guys please help??

**Comment by eddiemonge** [comment] 2015-02-25 18:10
possibly a duplicate of https://github.com/yeoman/yo/issues/292#issuecomment-75932264

But you should also update yo/node/npm and try again

**Closed** 2015-02-25 18:10 UTC

**Comment by kimpetersend1** [comment] 2015-02-26 10:12
I can't update yo as I can't install it via npm

On Wed, Feb 25, 2015 at 8:10 PM, Eddie Monge <notifications@github.com>
wrote:

> Closed #302 <https://github.com/yeoman/yo/issues/302>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yeoman/yo/issues/302#event-241906841>.
>



-- 
Kim Petersen
*kimpetersend1.com <http://kimpetersend1.com/>*

<https://www.facebook.com/SektorDesigns> <https://twitter.com/KimD1Petersen>
<http://www.behance.net/sektorDesigns> <http://slayerd1.deviantart.com>

**Comment by meonwax** [comment] 2015-02-26 14:48
See my comment in #292
