### ISSUE TITLE
Error running yo with Node.js 7.1 on windows 10 (Error: write EINVAL)

### ISSUE THREAD

**Issue by jochenvanwylick** [yeoman/yo#485] opened 2016-11-09 09:55 UTC
After updating Node to latest version ( 7.1.0 ) on my windows 10 box, I globally installed yeoman. After that, I get an error running the `yo` command:

![yeoman_error](https://cloud.githubusercontent.com/assets/3002474/20134202/e112f112-a66a-11e6-9523-44200e79773b.png)

Error message states:

```
D:\_code\test>yo
C:\Users\Jochen\AppData\Roaming\npm\node_modules\yo\node_modules\rx-lite\rx.lite.js:75
    throw e;
    ^

Error: write EINVAL
    at exports._errnoException (util.js:1022:11)
    at WriteStream.Socket._writeGeneric (net.js:715:26)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at MuteStream.ondata (stream.js:31:26)
    at emitOne (events.js:96:13)
    at MuteStream.emit (events.js:188:7)

D:\_code\test>npm -v
3.10.9

D:\_code\test>node -v
v7.1.0
```

**Comment by mischah** [comment] 2016-11-09 10:17
Mhmm. No Problems with Node 7.1.0 on Mac OS.

![image](https://cloud.githubusercontent.com/assets/441011/20135010/e885b12a-a66d-11e6-8487-c599b559fc5b.png)

**Comment by longjoel** [comment] 2016-11-10 02:36
I'm having the same problems.

```

Error: write EINVAL
    at exports._errnoException (util.js:1022:11)
    at WriteStream.Socket._writeGeneric (net.js:715:26)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at MuteStream.ondata (stream.js:31:26)
    at emitOne (events.js:96:13)
    at MuteStream.emit (events.js:188:7)
```

**Comment by SBoudrias** [comment] 2016-11-10 02:41
Got similar report on https://github.com/SBoudrias/Inquirer.js/issues/447

Looks like Windows and Node 7 don't play well with one of our dependency.

**Comment by mischah** [comment] 2016-11-10 09:58
Curiously enough I have no problems with Windows 10 and Node 7.1.0 running in a VM:

![image](https://cloud.githubusercontent.com/assets/441011/20172140/15be0784-a734-11e6-83df-17b45f21dad0.png)

So it would be awesome if @longjoel @jochenvanwylick or @Lichtjaeger could deep a little deeper to check if its only [rx-lite)](https://www.npmjs.com/package/rx-lite) which make problems. If so you could file a bug in the RxJS Repo.

**Comment by Lichtjaeger** [comment] 2016-11-10 10:24
Sorry, but that is not the same Windows Version I run. I have the latest Windows (10.0.14393 Build 14393 | Anniversary 2016).

These are my error states:

If I run `yo` in my cmd (or PowerShell too) it displays only black:
![schnappschuss_111016_111711_am](https://cloud.githubusercontent.com/assets/8598542/20173023/c8545274-a737-11e6-8572-05596a9c5e80.jpg)
After resize I get these error:
![schnappschuss_111016_111755_am](https://cloud.githubusercontent.com/assets/8598542/20173024/c8545f6c-a737-11e6-96cf-04e3b88d05d5.jpg)

If I run `yo <generator_name>` a get the following error:
![schnappschuss_111016_111900_am](https://cloud.githubusercontent.com/assets/8598542/20173026/c85d6c74-a737-11e6-90a8-576cd0e3d92d.jpg)

**Comment by mischah** [comment] 2016-11-10 11:58
Interestingly other users have similar errors with the combination of Windows 10 and Node 7.1.0 in with different packages:

* https://github.com/mochajs/mocha/issues/2577
* https://github.com/facebook/react-native/issues/10824
* https://github.com/electron/electron/issues/7919

I filed an issue in the Node.js repo: https://github.com/nodejs/node/issues/9542

**Comment by mischah** [comment] 2016-11-10 14:22
Current workaround: Get back to Node `7.0.0` or better use the current LTS version `6.9.x`

**Comment by diegolo** [comment] 2016-11-19 16:40
mischah, you are right!

**Comment by mischah** [comment] 2016-11-23 06:18
Closing this since Node 7.2 fixes this issue:
https://nodejs.org/en/blog/release/v7.2.0/

**Closed by mischah** 2016-11-23 06:18 UTC

**Comment by jochenvw** [comment] 2016-11-23 07:34
Yep - confirmed - thanks!

![image](https://cloud.githubusercontent.com/assets/17111555/20553802/9f4fa43a-b157-11e6-85a1-bdb0fe244fbc.png)

**Comment by HelloPb** [comment] 2016-12-02 11:16
I am getting error on windows 10, with node 7.2 latest
![image](https://cloud.githubusercontent.com/assets/3183406/20832203/0345cda2-b8dd-11e6-820e-de87ffb319c4.png)

**Comment by Lichtjaeger** [comment] 2016-12-02 11:26
I've made the experience that npm renames a file named ".gitignore" to ".npmignore".

You can confirm this by looking in the "C:\Users\Prasanna\AppData\Roaming\npm\node_modules\generator-fwsp-hydra\app\templates" directory.

It's a problem with the "generator-fwsp-hydra" module. Not with yo.

**Comment by emadum** [comment] 2017-01-05 18:35
Hi @HelloPb, just had this thread called to my attention. We fixed this issue a few days after your post, so if you haven't already, updating to the latest version of generator-fwsp-hydra will fix it.

Thanks!

**Comment by arigates** [comment] 2017-09-21 06:45
i have downgrade version, and now work perfectly
