### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by chenxuan199206** [yeoman/yo#527] opened 2017-07-07 12:36 UTC
root@chenxuan-ThinkPad-X240:/home/chenxuan# npm install --global yo
/root/.nvm/versions/node/v6.11.0/bin/yo -> /root/.nvm/versions/node/v6.11.0/lib/node_modules/yo/lib/cli.js
/root/.nvm/versions/node/v6.11.0/bin/yo-complete -> /root/.nvm/versions/node/v6.11.0/lib/node_modules/yo/lib/completion/index.js

> yo@2.0.0 postinstall /root/.nvm/versions/node/v6.11.0/lib/node_modules/yo
> yodoctor

Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Everything looks all right!

> spawn-sync@1.0.15 postinstall /root/.nvm/versions/node/v6.11.0/lib/node_modules/yo/node_modules/spawn-sync
> node postinstall

+ yo@2.0.0
added 364 packages in 38.484s
root@chenxuan-ThinkPad-X240:/home/chenxuan# yodoctor
yodoctor: command not found
root@chenxuan-ThinkPad-X240:/home/chenxuan# yo doctor
/root/.nvm/versions/node/v6.11.0/lib/node_modules/yo/node_modules/insight/node_modules/configstore/index.js:53
				throw err;
				^

Error: EACCES: permission denied, open '/root/.config/configstore/insight-yo.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Object.get (/root/.nvm/versions/node/v6.11.0/lib/node_modules/yo/node_modules/insight/node_modules/configstore/index.js:34:26)
    at Object.Configstore.get (/root/.nvm/versions/node/v6.11.0/lib/node_modules/yo/node_modules/insight/node_modules/configstore/index.js:81:13)
    at Insight.get (/root/.nvm/versions/node/v6.11.0/lib/node_modules/yo/node_modules/insight/lib/index.js:48:22)
    at Object.<anonymous> (/root/.nvm/versions/node/v6.11.0/lib/node_modules/yo/lib/cli.js:194:47)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

**Comment by PinkFLoyd92** [comment] 2017-07-07 17:19
Same here.

I already tried this
`  chmod g+rwx /root /root/.config /root/.config/configstore `
`  chown root:root /root/.config/ -R`

But I still can't use yo
```
  # yo -v                                                                                         !4113
/usr/lib/node_modules/yo/node_modules/insight/node_modules/configstore/index.js:53
				throw err;
				^

Error: EACCES: permission denied, open '/root/.config/configstore/insight-yo.json'
You don't have access to this file.

    at Object.fs.openSync (fs.js:651:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Configstore.get (/usr/lib/node_modules/yo/node_modules/insight/node_modules/configstore/index.js:34:26)
    at Configstore.get (/usr/lib/node_modules/yo/node_modules/insight/node_modules/configstore/index.js:81:13)
    at Insight.get (/usr/lib/node_modules/yo/node_modules/insight/lib/index.js:48:22)
    at Object.<anonymous> (/usr/lib/node_modules/yo/lib/cli.js:194:47)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)

```

**Comment by chenxuan199206** [comment] 2017-07-08 03:00
i think it's a bug for yo

**Comment by jorycn** [comment] 2017-07-19 03:52
same with me~~~0.0

**Comment by PinkFLoyd92** [comment] 2017-07-19 03:58
I was trying to launch it as a root user, yo forbids it. If you are experiencing the same issue being a common user maybe using chown in the executable could work.

**Comment by kevva** [comment] 2017-07-20 13:25
Duplicate of https://github.com/yeoman/yo/issues/348 https://github.com/yeoman/yo/issues/368 https://github.com/yeoman/yo/issues/369 https://github.com/yeoman/yo/issues/452.

**Closed by kevva** 2017-07-20 13:25 UTC
