### ISSUE TITLE
CLI doesn't work with Node v7.1.0

### ISSUE THREAD

**Issue by Lichtjaeger** [yeoman/yo#486] opened 2016-11-10 07:06 UTC
Hi,
still working with Node v7.0.0

OS: Windows 10 x64
Node: v7.1.0
npm: v3.10.8
yo: v1.8.5

**Comment by mischah** [comment] 2016-11-10 08:00
Thanks. It’s a duplicate of #485

**Comment by SBoudrias** [comment] 2016-11-11 08:01
Closing in favor or #485

**Closed by SBoudrias** 2016-11-11 08:01 UTC
