### ISSUE TITLE
Allow a generator to be set as the default so that sub-generators don't need to be specified.

### ISSUE THREAD

**Issue by danmartinez101** [yeoman/yo#310] opened 2015-03-20 01:28 UTC
I commonly use the same generator for stretches of time without the need to switch to another one. An example of this is when scaffolding out an angular application. I'll rapidly cycle through scaffolding and implementing a controller, service, view, directive, etc. 

`yo` is short and sweet, but `yo angular:controller` gets tedious pretty quickly. Defaulting to the last used generator and allowing this command to be shortened to `yo :controller` would be a nice improvement. :D 

Tab completion #222 could reduce the typing required even further, allowing for `yo :cont[tab]`, if it extends the list to sub-generators.

**Comment by SBoudrias** [comment] 2015-03-20 01:34
FYI duplicate of https://github.com/yeoman/generator/issues/14

It's not in our priority ATM, but we won't overlook a PR.

**Closed by SBoudrias** 2015-03-20 01:34 UTC
