### ISSUE TITLE
option alias not working?

### ISSUE THREAD

**Issue by BigstickCarpet** [yeoman/yo#319] opened 2015-04-27 21:19 UTC
I have an option with an alias, like this:

````javascript
module.exports = generators.Base.extend({
    constructor: function() {
        generators.Base.apply(this, arguments);
        this.option('opt', {alias: 'o', desc: 'testing aliases'});
    }
});
````

When I run `yo mygenerator --help`, I see the following output:

````
Usage:
  yo mygenerator:app [options] 

Options:
  -h,   --help        # Print the generator's options and usage
        --skip-cache  # Do not remember prompt answers
  -o,   --opt         # testing aliases
````

If I run my generator with `yo mygenerator --opt`, it works fine.  `generator.options.opt` is `true`, as expected.   But if I run my generator with `yo mygenerator -o`, it doesn't work.  `generator.options.opt` is `undefined`.   It seems like option aliases aren't working.   

The same applies for the `--help` option.  Running `yo --help` works fine, but `yo -h` doesn't work.

**Comment by SBoudrias** [comment] 2015-04-27 21:35
ping @sindresorhus might this be another regression due to switching from `nopt` to `meow`?

**Comment by sindresorhus** [comment] 2015-04-28 07:02
```
yo electron -o
```

Passes the following to `env.run(args, opts);`:

```
['electron']
{
  o: true
}
```

While with `nopt` it passed:

```
['electron']
{
  o: true,
  argv: {
    remain: ['electron'],
    cooked: ['electron', '-o'],
    original: ['electron', '-o']
  }
}
```

The `.run()` documentation is a bit limited, so not sure if this ever worked or should have. ?

http://yeoman.github.io/generator/Environment#run

**Comment by sindresorhus** [comment] 2015-04-28 07:02
> Running yo --help works fine, but yo -h doesn't work.

That's intentional.

**Comment by SBoudrias** [comment] 2015-04-28 07:26
Alright then, classifying as a bug. Feel free to dig the code if you want this resolved faster.

**Comment by BigstickCarpet** [comment] 2015-04-28 12:30
@sindresorhus - If it's intentional that `yo -h` doesn't work, then why is it listed as an option when in `yo --help`:

````
~: yo --help
Usage: yo GENERATOR [args] [options]

General options:
  -h, --help     # Print generator's options and usage
  -f, --force    # Overwrite files that already exist
````

**Comment by sindresorhus** [comment] 2015-04-28 14:18
I guess that help text needs to be updated.

**Comment by kevva** [comment] 2015-04-28 14:46
https://github.com/yeoman/yo/blob/master/lib/usage.txt

**Comment by BigstickCarpet** [comment] 2015-04-28 17:13
Latest version is 1.4.6, right?   It still shows the old usage text

**Comment by kevva** [comment] 2015-04-28 17:16
Hm, yeah. We haven't pushed out a new release since that changed.

**Comment by eddiemonge** [comment] 2015-04-28 19:24
It was updated https://github.com/yeoman/yo/commit/5905f6225e8ac1644dbcf58c5d45f16cc9f3c251
What is interactive help?

**Comment by SBoudrias** [comment] 2015-05-04 04:58
Hey, just checked into that issue. This is effectively a bug and it's not just about fixing the text. Aliases don't work anymore. When calling `this.option()` in a generator, there's always been a choice to add a shortname alias.

This feature should work as before. We'll need to investigate.

**Closed** 2015-12-25 22:21 UTC
Labels: actionnable, bug, easy

**Comment by Nitro-N** [comment] 2016-03-31 11:52
My yo version is 1.7.0, but I have same problem.
npm -v 3.8.3

**Comment by SBoudrias** [comment] 2016-03-31 18:22
@Nitro-N the yo version doesn't matter. It's about the `yeoman-generator` version.

**Comment by Nitro-N** [comment] 2016-03-31 18:31
@SBoudrias Yep! My mistake, sorry.
