### ISSUE TITLE
Your npm version is outdated.

### ISSUE THREAD

**Issue by shineycoding** [yeoman/yo#340] opened 2015-06-09 07:32 UTC
Yeoman Doctor
Running sanity checks on your system

√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ Node.js version
× npm version

Your npm version is outdated.

Upgrade to the latest version by running:
npm install -g npm

See this guide if you're having trouble upgrading:
https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows

√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory

Found potential issues on your machine :(

But I just installed a new version nodejs. 

λ yo --version && echo %PATH% %NODE_PATH% && node -e "console.log(process.platform, process.versions)" && ty
pe Gruntfile.js
1.4.7
D:\SOFTWARE_INSTALLATION\cmder\bin;D:\SOFTWARE_INSTALLATION\cmder\vendor\msysgit\bin;D:\SOFTWARE_INSTALLATION\cmder\vendor\msysgit\mingw\bin;D:\SOFTWARE_INSTALLATION\cmder\vendor\msysgit\cmd;D:\SOFTWARE_INSTALLATION\cmder\vendor\msysgit\share\vim\vim74;D:\SOFTWARE_INSTALLATION\cmder;D:\SOFTWARE_INSTALLATION\cmder\vendor\conemu-maximus5\ConEmu;D:\SOFTWARE_INSTALLATION\cmder\vendor\conemu-maximus5;C:\Program Files (x86)\Common Files\NetSarang;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;D:\JAVA\java8\jdk\bin;D:\JAVA\java8\jdk\jre\bin;D:\SOFTWARE_INSTALLATION\cygwin64\bin;D:\SOFTWARE_INSTALLATION\nodejs\node_modules\npm;D:\SOFTWARE_INSTALLATION\SlikSvn\bin;D:\apache-maven-3.1.0\bin;D:\apache-ant-1.9.4\bin;D:\Androidsdk\platform-tools;D:\Androidsdk\tools;D:\SOFTWARE_INSTALLATION\Scala\bin;D:\gradle-2.4/bin;C:\Program Files\MySQL\MySQL Server 5.6\bin;C:\Program Files (x86)\CloudFoundry;C:\Program Files (x86)\Heroku\bin;C:\Program Files (x86)\git\cmd;D:\SOFTWARE_INSTALLATION\Git\cmd;D:\SOFTWARE_INSTALLATION\nodejs\;D:\SERVERS\Ruby22-x64\bin;C:\Users\yxin\AppData\Roaming\npm %NODE_PATH%

win32 { http_parser: '2.3',
  node: '0.12.4',
  v8: '3.28.71.19',
  uv: '1.5.0',
  zlib: '1.2.8',
  modules: '14',
  openssl: '1.0.1m' }
The system cannot find the file specified.

**Comment by sindresorhus** [comment] 2015-06-09 09:54
Duplicate of https://github.com/yeoman/doctor/issues/19

**Closed by sindresorhus** 2015-06-09 09:54 UTC
