### ISSUE TITLE
Yo is succefully installed but i get an error when i run the command `yo`

### ISSUE THREAD

**Issue by zimski** [yeoman/yo#366] opened 2015-10-03 18:14 UTC
I get this when i start `yo`

the error is on `meow` module, `trim-newlines` submodule
```
$ yo
/home/zimski/.nvm-fish/v0.12.7/lib/node_modules/yo/node_modules/meow/node_modules/trim-newlines/index.js:8
	return x.replace(/^[\r\n]+/, '');
	         ^
TypeError: undefined is not a function
    at Function.fn.start (/home/zimski/.nvm-fish/v0.12.7/lib/node_modules/yo/node_modules/meow/node_modules/trim-newlines/index.js:8:11)
    at module.exports (/home/zimski/.nvm-fish/v0.12.7/lib/node_modules/yo/node_modules/meow/node_modules/trim-newlines/index.js:4:19)
    at module.exports (/home/zimski/.nvm-fish/v0.12.7/lib/node_modules/yo/node_modules/meow/index.js:33:20)
    at Object.<anonymous> (/home/zimski/.nvm-fish/v0.12.7/lib/node_modules/yo/lib/cli.js:15:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
````

dependency list:
```
yo@1.4.8 /home/zimski/.nvm-fish/v0.12.7/lib/node_modules/yo
├── titleize@1.0.0
├── array-uniq@1.0.2
├── figures@1.4.0
├── async@1.4.2
├── humanize-string@1.0.1 (decamelize@1.0.0)
├── opn@3.0.2 (object-assign@3.0.0)
├── user-home@2.0.0 (os-homedir@1.0.1)
├── string-length@1.0.1 (strip-ansi@3.0.0)
├── sort-on@1.2.2 (arrify@1.0.0, dot-prop@2.2.0)
├── yeoman-character@1.0.1 (supports-color@1.3.1)
├── findup@0.1.5 (commander@2.1.0, colors@0.6.2)
├── configstore@1.2.1 (os-tmpdir@1.0.1, object-assign@3.0.0, graceful-fs@4.1.2, xdg-basedir@2.0.0, uuid@2.0.1, osenv@0.1.3, mkdirp@0.5.1, write-file-atomic@1.1.3)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── repeating@1.1.3 (is-finite@1.0.1)
├── root-check@1.0.0 (downgrade-root@1.1.0, sudo-block@1.2.0)
├── yosay@1.0.5 (ansi-regex@1.1.1, ansi-styles@2.1.0, word-wrap@1.1.0, strip-ansi@2.0.1, pad-component@0.0.1, taketalk@1.0.0, minimist@1.2.0, string-width@1.0.1)
├── update-notifier@0.5.0 (is-npm@1.0.0, latest-version@1.0.1, semver-diff@2.0.0)
├── fullname@1.1.1 (npmconf@2.1.2)
├── inquirer@0.9.0 (strip-ansi@3.0.0, ansi-regex@2.0.0, cli-width@1.0.1, through@2.3.8, readline2@0.1.1, run-async@0.1.0, rx-lite@2.5.2)
├── got@4.2.0 (lowercase-keys@1.0.0, is-stream@1.0.1, timed-out@2.0.0, is-redirect@1.0.0, is-plain-obj@1.0.0, prepend-http@1.0.3, unzip-response@1.0.0, object-assign@3.0.0, node-status-codes@1.0.0, create-error-class@2.0.1, pinkie-promise@1.0.0, parse-json@2.2.0, read-all-stream@3.0.1, duplexify@3.4.2)
├── package-json@1.2.0 (registry-url@3.0.3, got@3.3.1)
├── npm-keyword@1.2.0 (registry-url@3.0.3, got@3.3.1)
├── cross-spawn@0.4.1 (lru-cache@2.7.0, spawn-sync@1.0.13)
├── meow@3.4.0 (trim-newlines@1.0.0, loud-rejection@1.0.0, object-assign@4.0.1, camelcase-keys@1.0.0, minimist@1.2.0, redent@1.0.0, read-pkg-up@1.0.1)
├── lodash@3.10.1
├── insight@0.6.0 (object-assign@2.1.1, async@0.9.2, lodash.debounce@3.1.1, os-name@1.0.3, tough-cookie@1.2.0, request@2.64.0, inquirer@0.8.5)
├── yeoman-environment@1.2.7 (escape-string-regexp@1.0.3, log-symbols@1.0.2, diff@1.4.0, text-table@0.2.0, untildify@2.1.0, debug@2.2.0, mem-fs@1.1.0, globby@2.1.0, grouped-queue@0.3.0, inquirer@0.8.5)
└── yeoman-doctor@1.4.0 (object-values@1.0.0, log-symbols@1.0.2, user-home@1.1.1, each-async@1.1.1, semver@4.3.6, bin-version-check@2.1.0, twig@0.8.2
```

**Comment by sindresorhus** [comment] 2015-10-03 18:17
Duplicate of https://github.com/yeoman/yo/issues/365.

**Closed by sindresorhus** 2015-10-03 18:17 UTC
