### ISSUE TITLE
Renaming files with "gulp-rename" in "registerTransformStream" causes "Error: write after end"

### ISSUE THREAD

**Issue by asmagin** [yeoman/yo#577] opened 2018-05-21 22:35 UTC
## Type of issue
Bug
----
## My environment

* *OS version/details*: `Windows 10 64-bit`
* *Node version:* `v8.11.2`
* *npm version:* `6.0.1`
* *Version of yo :* `2.0.2`

## Expected behavior

Rename of a file in `registerTransformStream` doesn't cause errors.

## Current behavior

when I'm trying to rename a file with `gulp-rename` in `registerTransformStream`  I see an error after the write method execution.

## Steps to reproduce the behavior
``` js
  self.registerTransformStream(
    rename(function (path) {
      path.basename = path.basename.replace(/(SolutionX)/g, self.options.solutionName)
      path.dirname = path.dirname.replace(/(SolutionX)/g, self.options.solutionName)
    })
  );
``` 

## Command line output
``` powershell
  yeoman:generator Running writing +0ms
{ dot: true,
  sync: true,
  debug: true,
  ignore:
   [ '**/code/bin/**/*.*',
     '**/code/obj/**/*.*',
     '**/*.user',
     '**/src/packages/**/*',
     '**/src/node_modules/**/*',
     '**/.vs*/**/*' ] }
Old:    package.json
   create package.json
Old:    .prettierrc
   create .prettierrc
Old:    build.cake
   create build.cake
Old:    build.ps1
   create build.ps1
Old:    LICENSE
   create LICENSE
Old:    publishsettings.targets
   create publishsettings.targets
Old:    readme.md
   create readme.md
Old:    Settings.StyleCop
   create Settings.StyleCop
Old:    SolutionX.sln     # << ------ original file
   create MySolution.sln  # << ------ renamed file
Old:    tsconfig.json
   create tsconfig.json
Old:    tslint.json
   create tslint.json
Old:    webpack.config.js
   create webpack.config.js
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at Transform.Writable.write (_stream_writable.js:287:5)
    at DestroyableTransform.ondata (D:\.projects\my-generator\scaffold\node_modules\readable-stream\lib\_stream_readable.js:619:20)
    at emitOne (events.js:116:13)
    at DestroyableTransform.emit (events.js:211:7)
    at addChunk (D:\.projects\my-generator\scaffold\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (D:\.projects\my-generator\scaffold\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (D:\.projects\my-generator\scaffold\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at DestroyableTransform.Transform.push (D:\.projects\my-generator\scaffold\node_modules\readable-stream\lib\_stream_transform.js:148:32)
    at DestroyableTransform._transform (D:\.projects\my-generator\scaffold\node_modules\mem-fs-editor\lib\actions\commit.js:34:12)
    at DestroyableTransform.Transform._read (D:\.projects\my-generator\scaffold\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (D:\.projects\my-generator\scaffold\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (D:\.projects\my-generator\scaffold\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (D:\.projects\my-generator\scaffold\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (D:\.projects\my-generator\scaffold\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at DestroyableTransform.ondata (C:\Users\asmagin\AppData\Roaming\npm\node_modules\yo\node_modules\readable-stream\lib\_stream_readable.js:619:20)
```

**Comment by UncleWalt** [comment] 2018-05-27 11:54
This seems to be caused by recent changes in **gulp-rename** (current version 1.2.3). Older versions work just fine. In my case i had to pin gulp-rename to 1.2.2 to fix my generators.

**Comment by SBoudrias** [comment] 2018-05-29 02:27
Thanks @UncleWalt, I'll close this issue then.

**Closed by SBoudrias** 2018-05-29 02:27 UTC

**Comment by afeiship** [comment] 2018-05-29 03:57
@UncleWalt thanks, it works.

**Comment by asmagin** [comment] 2018-05-29 14:15
I tried `registerTransformStream` without `gulp-rename`, providing custom transform stream and it produces the same error.

**Comment by Toilal** [comment] 2018-10-24 06:13
This is still an issue with gulp-rename `1.4.0`

**Comment by jariwalakrunal1983** [comment] 2019-11-12 04:00
`registerTransformStream` with `gulp-rename` is still an issue (getting an error in gulp-rename 1.2.2) but I get it working with glob. Hope this will help someone to get their job done. 

```
const glob = require('glob');

writing() {
    const files = glob.sync('**', { dot: true, nodir: true, cwd: this.templatePath() })
    for (let i in files) {
        this.fs.copyTpl(
            this.templatePath(files[i]),
            this.destinationPath( this.props.destinationFolderPath + '\\' + files[i].replace(/__fileName__/g,this.props.fileName)),
            this.props
        )
    }
}
```

**Comment by xenogenesi** [comment] 2021-04-11 21:25
Still an issue with gulp-rename `2.0.0`
